[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
disabled = '!has("Python3")'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
disabled = '!has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'itchyny/vim-haskell-sort-import'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

# Operators
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Rip-Rip/clang_complete'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'nbouscal/vim-stylish-haskell'

#colorscheam
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'oka-h/yozakura.vim'

[[plugins]]
repo = 'jdkanani/vim-material-theme'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'rhysd/committia.vim'

[[plugins]]
repo = 'idanarye/vim-merginal'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

